### ISSUE TITLE
How to call this in angular 2 

### ISSUE THREAD

**Issue by rrohitesh** [remy/polyfills#54] opened 2017-03-28 06:36 UTC
Hello All,
 I am trying to call this in my angular 2 component 
like:

require('../../../style/vendors/EventSource.js');

		let es = new EventSource(URL);

But, i am getting the exception that event source :ErrorUncaught (in promise): TypeError: EventSource is not a constructor
TypeError: EventSource is not a constructor

Please suggest me i am doing this in correctly or not?

**Comment by remy** [comment] 2017-03-28 06:45
No clue, pretty much why I've never got on with Angular to be honest. Sorry i cant be more help. 

Closing as it's not a bug with the lib, but I'd suggest reaching out to StackOverflow community?

**Closed by remy** 2017-03-28 06:45 UTC
